{
 "title": "Task_Dashboard",
 "time": { "from": "2024-09-22T16:25:27.000Z", "to": "2024-09-22T16:40:31.000Z" },
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "No. of CPU",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"system\"}) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "max by (instance, nodename) (\r\n  node_uname_info\r\n  * on(instance) group_left(uptime_hours)\r\n  (((time() - node_boot_time_seconds) / 3600) > 0)\r\n  * on(instance) group_left(connections)\r\n node_netstat_Tcp_CurrEstab\r\n)",
     "legendFormat": "auto"
    }
   ]
  },
  {
   "title": "Network Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 4 },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!=\"lo\"}[5m])) by (instance)",
     "legendFormat": "NW Bandwidth Sent - {{instance}}"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!=\"lo\"}[5m])) by (instance)",
     "legendFormat": "NW Bandwidth Received - {{instance}}"
    }
   ]
  },
  {
   "title": "Memory Info",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "100 * (node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Cached_bytes - node_memory_Buffers_bytes) / node_memory_MemTotal_bytes",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}